### ISSUE TITLE
Error: 'GetClusters' is not an exported object from 'namespace:FlowSOM'

### ISSUE THREAD

**Issue by SansMorel** [saeyslab/CytoNorm#1]
When running testCV() I get the error in the title. How do I import the GetClusters function?
Do I need a specific version or package with FlowSOM?

**Comment by SofieVG** [comment]
Dear Sturla,

It might be necessary to install FlowSOM also from github instead of using
the bioconductor version (although I think it should be available in the
latest version as well).
Try devtools::install_github("saeyslab/FlowSOM")

Kind regards,
Sofie

**Comment by SansMorel** [comment]
Thanks!
I will try your suggestion and let you know if it worked @SofieVG

**Comment by SansMorel** [comment]
The suggestion worked. Thanks!
