### ISSUE TITLE
License and version

### ISSUE THREAD

**Issue by abotzki** [saeyslab/CytoNorm#17]
Hi, with respect to adding the tool to bio.tools I am wondering whether you could specify a license and a version of the tool? Thanks.

**Comment by SofieVG** [comment]
Dear Alexander,

This information can be found in the description file. The current version
is 0.0.5 and the license GPL (>= 2).

All the best,
Sofie

**Comment by abotzki** [comment]
Thanks Sofie. I will try to tweak our code so that it reads the description file if present in the repo, too. Cheers, Alex

**Comment by SamGG** [comment]
Sofie's code is purely following the standard of creating a R package.
If you have already incorporated R package at bio.tools, this should be straightforward.
Best.
