### ISSUE TITLE
K-mean clustering instead of FlowSOM

### ISSUE THREAD

**Issue by EAC-T** [saeyslab/CytoNorm#19]
Hi everyone,
For some reason FlowSOM can't cluster my T cells into naive and memory, K-mean can, is there a way to use K-mean clustering instead? 
Thank you a lot

**Comment by tomashhurst** [comment]
Hi @EAC-T ,

Our package Spectre uses CytoNorm as the primary batch alignment method. In an upcoming update, we'll have an update where you can perform alignment with whatever clustering approach you want (K-means, phenograph, etc). It's not exactly the same implementation as CytoNorm, but it's similar. Would this work for you?

Tom

**Comment by EAC-T** [comment]
Hi @tomashhurst 

Yes that would be great! 

Thank you

**Comment by SofieVG** [comment]
Hi @EAC-T ,

I'm afraid that would have been out of scope for our implementation, so I'm very happy to hear @tomashhurst will be able to provide this in the Spectre package!

All the best,
Sofie
