### ISSUE TITLE
combine cytonorm with PeacoQC?

### ISSUE THREAD

**Issue by onecarbon** [saeyslab/CytoNorm#27]
Thanks for the software!

I was wondering if you have a recommendation for combining your cytonorm workflow with PeacoQC (also from your group)? It looks like cytonorm estimates it's own per-channel transformations, but I would like to input (PeacoQC) cleaned files which do not have such nuanced transformations. Or do you recommend this is done in a different order? thanks for any advice.

**Comment by SofieVG** [comment]
Hi,

I feel like there are several elements going into this, so I'll answer in a few points:
- Combining PeacoQC and CytoNorm. This should certainly be possible. I would indeed recommend to first clean the files with PeacoQC, so any technical issues are resolved and the control samples are optimally comparable (e.g. if you take a control along in each batch, but in one of them a blockage happens or the tube runs dry, you do not expect this to also happen in the other batch, or be representative for all samples in the batch). 
- Transformation in PeacoQC. Files would typically be transformed before passing them to PeacoQC, as in the transformed space the peaks are easier to detect. You can do this with whichever transformation you would prefer (can be as nuanced or as generic as relevant for your data). In the end you can also get the indices of the cells to be kept, so you can also decide to take this subset from the raw files, without the transformation, if this would be more straight forward for the rest of your pipeline. 
- Transformation in CytoNorm. In the examples provided, we use a simple asinh transform with cofactor 5, as this was demonstrated on mass cytometry data. However, in the case where you want more nuanced transformations, it would be easiest to set the transformList (and reverseTransformList were applicable) to NULL, so no transformation is applied in the CytoNorm algorithm. Then you would just need to transform the input data upfront. For example, you could use the already transformed files, that you got as a result from PeacoQC. Note that in that case the end files produced by CytoNorm will still be transformed (so you would need to reverse the transformation yourself if you want to go back to raw values). 

I hope this helps!
All the best,
Sofie

**Comment by onecarbon** [comment]
Thanks for the detailed answer, that is very helpful! I really appreciate it.
