### ISSUE TITLE
testCV() Error in t.default(data) : argument is not a matrix

### ISSUE THREAD

**Issue by SameOldSamOld** [saeyslab/CytoNorm#29]
Hi, 

I was following your usage guide and this function was producing the error above for me.

I noticed that the format of fsom provided to testCV() didn't seem to be correct, fsom$FlowSOM needed to be provided.

Error code:
`cvs <- testCV(fsom,
              cluster_values = c(5, 10, 15), plot = FALSE)`

Fix:
`cvs <- testCV(fsom$FlowSOM,
              cluster_values = c(5, 10, 15), plot = FALSE)`

**Comment by tomashhurst** [comment]
@SameOldSamOld from memory that extra fsom object structure was in the previous version of CytoNorm, what version are you on now?

**Comment by SameOldSamOld** [comment]
I'll have to check on Monday. I had recently updated with dev
tools::install_github() this week.

**Comment by SameOldSamOld** [comment]
I am currently using

- flowCore_2.2.0
- CytoNorm_0.0.7

**Comment by SameOldSamOld** [comment]
I was using the wrong FlowSOM package version. 

I kept trying to install the latest CytoNorm version (0.0.7) from github and the latest version of FlowSOM (1.22.0) from Bioconductor. 

I've now downloaded the latest version of each package from the saeslab github, restarted R, and am having no issue.
Thanks!
