### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SamGG** [saeyslab/CytoNorm#6]
Hi,
The link to the graphical overview is
man/figures/algorithm_overview.PNG
This will make the package even more attractive.
Best,
Samuel

**Comment by SofieVG** [comment]
Thank you!

**Comment by SamGG** [comment]
In case you redo the screenshot, do it in presentation mode to avoid the underlining of the spelling corrector.
Very nice work, and thanks for releasing the gating strategy along with FCS.
Best.
